/**
 * Copyright 2005-2013 Restlet S.A.S.
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: Apache 2.0 or LGPL 3.0 or LGPL 2.1 or CDDL 1.0 or EPL
 * 1.0 (the "Licenses"). You can select the license that you prefer but you may
 * not use this file except in compliance with one of these Licenses.
 * 
 * You can obtain a copy of the Apache 2.0 license at
 * http://www.opensource.org/licenses/apache-2.0
 * 
 * You can obtain a copy of the LGPL 3.0 license at
 * http://www.opensource.org/licenses/lgpl-3.0
 * 
 * You can obtain a copy of the LGPL 2.1 license at
 * http://www.opensource.org/licenses/lgpl-2.1
 * 
 * You can obtain a copy of the CDDL 1.0 license at
 * http://www.opensource.org/licenses/cddl1
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://www.restlet.com/products/restlet-framework
 * 
 * Restlet is a registered trademark of Restlet S.A.S.
 */

package htw.bui.openreskit.domain.organisation;


import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:7000/OpenResKitHub/$metadata">Metadata of the target OData service</a>
*
*/

@JsonTypeInfo(use=JsonTypeInfo.Id.NAME, include=JsonTypeInfo.As.PROPERTY, property="odata.type")
@JsonIgnoreProperties(ignoreUnknown = true)
public class Employee extends ResponsibleSubject {

    @JsonProperty("FirstName")
	private String firstName;
    
    @JsonProperty("LastName")
    private String lastName;
    
    @JsonProperty("Number")
    private String number;
    
    @JsonProperty("Groups")
    private List<EmployeeGroup> groups;
    
  
    /**
     * Constructor without parameter.
     * 
     */
    public Employee() {
        super();
    }

   /**
    * Returns the value of the "firstName" attribute.
    *
    * @return The value of the "firstName" attribute.
    */
   public String getFirstName() {
      return firstName;
   }
   /**
    * Returns the value of the "lastName" attribute.
    *
    * @return The value of the "lastName" attribute.
    */
   public String getLastName() {
      return lastName;
   }
   /**
    * Returns the value of the "number" attribute.
    *
    * @return The value of the "number" attribute.
    */
   public String getNumber() {
      return number;
   }
   /**
    * Returns the value of the "groups" attribute.
    *
    * @return The value of the "groups" attribute.
    */
   public List<EmployeeGroup> getGroups() {
      return groups;
   }
   
   /**
    * Sets the value of the "firstName" attribute.
    *
    * @param firstName
    *     The value of the "firstName" attribute.
    */
   public void setFirstName(String firstName) {
      this.firstName = firstName;
   }
   /**
    * Sets the value of the "lastName" attribute.
    *
    * @param lastName
    *     The value of the "lastName" attribute.
    */
   public void setLastName(String lastName) {
      this.lastName = lastName;
   }
   /**
    * Sets the value of the "number" attribute.
    *
    * @param number
    *     The value of the "number" attribute.
    */
   public void setNumber(String number) {
      this.number = number;
   }
   /**
    * Sets the value of the "groups" attribute.
    *
    * @param groups"
    *     The value of the "groups" attribute.
    */
   public void setGroups(List<EmployeeGroup> groups) {
      this.groups = groups;
   }

}