/**
 * Copyright 2005-2013 Restlet S.A.S.
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: Apache 2.0 or LGPL 3.0 or LGPL 2.1 or CDDL 1.0 or EPL
 * 1.0 (the "Licenses"). You can select the license that you prefer but you may
 * not use this file except in compliance with one of these Licenses.
 * 
 * You can obtain a copy of the Apache 2.0 license at
 * http://www.opensource.org/licenses/apache-2.0
 * 
 * You can obtain a copy of the LGPL 3.0 license at
 * http://www.opensource.org/licenses/lgpl-3.0
 * 
 * You can obtain a copy of the LGPL 2.1 license at
 * http://www.opensource.org/licenses/lgpl-2.1
 * 
 * You can obtain a copy of the CDDL 1.0 license at
 * http://www.opensource.org/licenses/cddl1
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://www.restlet.com/products/restlet-framework
 * 
 * Restlet is a registered trademark of Restlet S.A.S.
 */

package htw.bui.openreskit.domain.organisation;


import java.util.Date;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:7000/OpenResKitHub/$metadata">Metadata of the target OData service</a>
*
*/
public class Series {

	
	@JsonProperty("Id")
	private int id;
	
	@JsonProperty("Begin")
	private Date begin;
	
	@JsonProperty("Cycle")
	private int cycle;
	
	@JsonProperty("End")
	private Date end;
	
	@JsonProperty("EndsWithDate")
	private boolean endsWithDate;
	
	@JsonProperty("IsAllDay")
    private boolean isAllDay;
	
	@JsonProperty("IsWeekdayRecurrence")
	private boolean isWeekdayRecurrence;
	
	@JsonProperty("Name")
	private String name;
	
	@JsonProperty("NumberOfRecurrences")
	private int numberOfRecurrences;
	
	@JsonProperty("RecurrenceInterval")
	private int recurrenceInterval;
	
	@JsonProperty("Repeat")
	private boolean repeat;
	
	@JsonProperty("RepeatUntilDate")
    private Date repeatUntilDate;
	
	@JsonProperty("SeriesColor")
    private SeriesColor seriesColor;
	
	//TODO
    //@ForeignCollectionField (eager = true)
    //private List<DayOfWeek> weekDays;

    /**
     * Constructor without parameter.
     * 
     */
    public Series() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public Series(int id) {
        this();
        this.id = id;
    }

   /**
    * Returns the value of the "begin" attribute.
    *
    * @return The value of the "begin" attribute.
    */
   public Date getBegin() {
      return begin;
   }
   /**
    * Returns the value of the "cycle" attribute.
    *
    * @return The value of the "cycle" attribute.
    */
   public int getCycle() {
      return cycle;
   }
   /**
    * Returns the value of the "end" attribute.
    *
    * @return The value of the "end" attribute.
    */
   public Date getEnd() {
      return end;
   }
   /**
    * Returns the value of the "endsWithDate" attribute.
    *
    * @return The value of the "endsWithDate" attribute.
    */
   public boolean getEndsWithDate() {
      return endsWithDate;
   }
   /**
    * Returns the value of the "id" attribute.
    *
    * @return The value of the "id" attribute.
    */
   public int getId() {
      return id;
   }
   /**
    * Returns the value of the "isAllDay" attribute.
    *
    * @return The value of the "isAllDay" attribute.
    */
   public boolean getIsAllDay() {
      return isAllDay;
   }
   /**
    * Returns the value of the "isWeekdayRecurrence" attribute.
    *
    * @return The value of the "isWeekdayRecurrence" attribute.
    */
   public boolean getIsWeekdayRecurrence() {
      return isWeekdayRecurrence;
   }
   /**
    * Returns the value of the "name" attribute.
    *
    * @return The value of the "name" attribute.
    */
   public String getName() {
      return name;
   }
   /**
    * Returns the value of the "numberOfRecurrences" attribute.
    *
    * @return The value of the "numberOfRecurrences" attribute.
    */
   public int getNumberOfRecurrences() {
      return numberOfRecurrences;
   }
   /**
    * Returns the value of the "recurrenceInterval" attribute.
    *
    * @return The value of the "recurrenceInterval" attribute.
    */
   public int getRecurrenceInterval() {
      return recurrenceInterval;
   }
   /**
    * Returns the value of the "repeat" attribute.
    *
    * @return The value of the "repeat" attribute.
    */
   public boolean getRepeat() {
      return repeat;
   }
   /**
    * Returns the value of the "repeatUntilDate" attribute.
    *
    * @return The value of the "repeatUntilDate" attribute.
    */
   public Date getRepeatUntilDate() {
      return repeatUntilDate;
   }
   /**
    * Returns the value of the "seriesColor" attribute.
    *
    * @return The value of the "seriesColor" attribute.
    */
   public SeriesColor getSeriesColor() {
      return seriesColor;
   }
   
   /**
    * Returns the value of the "weekDays" attribute.
    *
    * @return The value of the "weekDays" attribute.
    */
//   public List<DayOfWeek> getWeekDays() {
//      return weekDays;
//   }
//   
   /**
    * Sets the value of the "begin" attribute.
    *
    * @param begin
    *     The value of the "begin" attribute.
    */
   public void setBegin(Date begin) {
      this.begin = begin;
   }
   /**
    * Sets the value of the "cycle" attribute.
    *
    * @param cycle
    *     The value of the "cycle" attribute.
    */
   public void setCycle(int cycle) {
      this.cycle = cycle;
   }
   /**
    * Sets the value of the "end" attribute.
    *
    * @param end
    *     The value of the "end" attribute.
    */
   public void setEnd(Date end) {
      this.end = end;
   }
   /**
    * Sets the value of the "endsWithDate" attribute.
    *
    * @param endsWithDate
    *     The value of the "endsWithDate" attribute.
    */
   public void setEndsWithDate(boolean endsWithDate) {
      this.endsWithDate = endsWithDate;
   }
   /**
    * Sets the value of the "id" attribute.
    *
    * @param id
    *     The value of the "id" attribute.
    */
   public void setId(int id) {
      this.id = id;
   }
   /**
    * Sets the value of the "isAllDay" attribute.
    *
    * @param isAllDay
    *     The value of the "isAllDay" attribute.
    */
   public void setIsAllDay(boolean isAllDay) {
      this.isAllDay = isAllDay;
   }
   /**
    * Sets the value of the "isWeekdayRecurrence" attribute.
    *
    * @param isWeekdayRecurrence
    *     The value of the "isWeekdayRecurrence" attribute.
    */
   public void setIsWeekdayRecurrence(boolean isWeekdayRecurrence) {
      this.isWeekdayRecurrence = isWeekdayRecurrence;
   }
   /**
    * Sets the value of the "name" attribute.
    *
    * @param name
    *     The value of the "name" attribute.
    */
   public void setName(String name) {
      this.name = name;
   }
   /**
    * Sets the value of the "numberOfRecurrences" attribute.
    *
    * @param numberOfRecurrences
    *     The value of the "numberOfRecurrences" attribute.
    */
   public void setNumberOfRecurrences(int numberOfRecurrences) {
      this.numberOfRecurrences = numberOfRecurrences;
   }
   /**
    * Sets the value of the "recurrenceInterval" attribute.
    *
    * @param recurrenceInterval
    *     The value of the "recurrenceInterval" attribute.
    */
   public void setRecurrenceInterval(int recurrenceInterval) {
      this.recurrenceInterval = recurrenceInterval;
   }
   /**
    * Sets the value of the "repeat" attribute.
    *
    * @param repeat
    *     The value of the "repeat" attribute.
    */
   public void setRepeat(boolean repeat) {
      this.repeat = repeat;
   }
   /**
    * Sets the value of the "repeatUntilDate" attribute.
    *
    * @param repeatUntilDate
    *     The value of the "repeatUntilDate" attribute.
    */
   public void setRepeatUntilDate(Date repeatUntilDate) {
      this.repeatUntilDate = repeatUntilDate;
   }
   /**
    * Sets the value of the "seriesColor" attribute.
    *
    * @param seriesColor"
    *     The value of the "seriesColor" attribute.
    */
   public void setSeriesColor(SeriesColor seriesColor) {
      this.seriesColor = seriesColor;
   }

   /**
    * Sets the value of the "weekDays" attribute.
    *
    * @param weekDays"
    *     The value of the "weekDays" attribute.
    */
//   public void setWeekDays(List<DayOfWeek> weekDays) {
//      this.weekDays = weekDays;
//   }

}