/**
 * Copyright 2005-2013 Restlet S.A.S.
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: Apache 2.0 or LGPL 3.0 or LGPL 2.1 or CDDL 1.0 or EPL
 * 1.0 (the "Licenses"). You can select the license that you prefer but you may
 * not use this file except in compliance with one of these Licenses.
 * 
 * You can obtain a copy of the Apache 2.0 license at
 * http://www.opensource.org/licenses/apache-2.0
 * 
 * You can obtain a copy of the LGPL 3.0 license at
 * http://www.opensource.org/licenses/lgpl-3.0
 * 
 * You can obtain a copy of the LGPL 2.1 license at
 * http://www.opensource.org/licenses/lgpl-2.1
 * 
 * You can obtain a copy of the CDDL 1.0 license at
 * http://www.opensource.org/licenses/cddl1
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://www.restlet.com/products/restlet-framework
 * 
 * Restlet is a registered trademark of Restlet S.A.S.
 */

package htw.bui.openreskit.domain.organisation;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:7000/OpenResKitHub/$metadata">Metadata of the target OData service</a>
*
*/
public class SeriesColor {

	@JsonProperty("Id")
	private int id;
	
	@JsonProperty("R")
	private byte r;
	
	@JsonProperty("B")
	private byte b;
	
	@JsonProperty("G")
	private byte g;
    
    

    /**
     * Constructor without parameter.
     * 
     */
    public SeriesColor() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public SeriesColor(int id) {
        this();
        this.id = id;
    }

   /**
    * Returns the value of the "b" attribute.
    *
    * @return The value of the "b" attribute.
    */
   public byte getB() {
      return b;
   }
   /**
    * Returns the value of the "g" attribute.
    *
    * @return The value of the "g" attribute.
    */
   public byte getG() {
      return g;
   }
   /**
    * Returns the value of the "id" attribute.
    *
    * @return The value of the "id" attribute.
    */
   public int getId() {
      return id;
   }
   /**
    * Returns the value of the "r" attribute.
    *
    * @return The value of the "r" attribute.
    */
   public byte getR() {
      return r;
   }
   /**
    * Sets the value of the "b" attribute.
    *
    * @param b
    *     The value of the "b" attribute.
    */
   public void setB(byte b) {
      this.b = b;
   }
   /**
    * Sets the value of the "g" attribute.
    *
    * @param g
    *     The value of the "g" attribute.
    */
   public void setG(byte g) {
      this.g = g;
   }
   /**
    * Sets the value of the "id" attribute.
    *
    * @param id
    *     The value of the "id" attribute.
    */
   public void setId(int id) {
      this.id = id;
   }
   /**
    * Sets the value of the "r" attribute.
    *
    * @param r
    *     The value of the "r" attribute.
    */
   public void setR(byte r) {
      this.r = r;
   }
}