/**
 * Copyright 2005-2013 Restlet S.A.S.
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: Apache 2.0 or LGPL 3.0 or LGPL 2.1 or CDDL 1.0 or EPL
 * 1.0 (the "Licenses"). You can select the license that you prefer but you may
 * not use this file except in compliance with one of these Licenses.
 * 
 * You can obtain a copy of the Apache 2.0 license at
 * http://www.opensource.org/licenses/apache-2.0
 * 
 * You can obtain a copy of the LGPL 3.0 license at
 * http://www.opensource.org/licenses/lgpl-3.0
 * 
 * You can obtain a copy of the LGPL 2.1 license at
 * http://www.opensource.org/licenses/lgpl-2.1
 * 
 * You can obtain a copy of the CDDL 1.0 license at
 * http://www.opensource.org/licenses/cddl1
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://www.restlet.com/products/restlet-framework
 * 
 * Restlet is a registered trademark of Restlet S.A.S.
 */

package htw.bui.openreskit.domain.meter;

import htw.bui.openreskit.domain.organisation.ScheduledTask;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;


/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="http://141.45.165.40:7000/OpenResKitHub/$metadata">Metadata of the target OData service</a>
*
*/
@JsonTypeInfo(use=JsonTypeInfo.Id.NAME, include=JsonTypeInfo.As.PROPERTY, property="odata.type")
@JsonIgnoreProperties(ignoreUnknown = true)
public class MeterReading extends ScheduledTask implements Comparable<MeterReading>{

    @JsonProperty("CounterReading")
	private double counterReading;
    
    @JsonProperty("ReadingMeter")
    private Meter readingMeter;

    @JsonProperty
	private boolean manipulated;

	public boolean isManipulated() {
		return manipulated;
	}
	public void setManipulated(boolean manipulated) {
		this.manipulated = manipulated;
	}
	
    /**
     * Constructor without parameter.
     * 
     */
    public MeterReading() {
        super();
    }

   /**
    * Returns the value of the "counterReading" attribute.
    *
    * @return The value of the "counterReading" attribute.
    */
   public double getCounterReading() {
      return counterReading;
   }
   /**
    * Returns the value of the "readingMeter" attribute.
    *
    * @return The value of the "readingMeter" attribute.
    */
   public Meter getReadingMeter() {
      return readingMeter;
   }
   
   /**
    * Sets the value of the "counterReading" attribute.
    *
    * @param counterReading
    *     The value of the "counterReading" attribute.
    */
   public void setCounterReading(double counterReading) {
      this.counterReading = counterReading;
   }
   /**
    * Sets the value of the "readingMeter" attribute.
    *
    * @param readingMeter"
    *     The value of the "readingMeter" attribute.
    */
   public void setReadingMeter(Meter readingMeter) {
      this.readingMeter = readingMeter;
   }

   @Override
   public int compareTo(MeterReading mr) {
	   return this.getDueDate().compareTo(mr.getDueDate());
   }

}